### ISSUE TITLE
Conspiratio.Lib aufbauen: Code refaktorisieren und veröffentlichen

### ISSUE THREAD

**Issue by SirTobyB** [Conspiratio/Conspiratio.Lib#3]
Vorbereitungen treffen, um möglichst viel Code auf GitHub veröffentlichen zu können. Dafür muss noch einiges refactorisiert und optimiert werden. Gleichzeitig möchte ich erreichen, dass dabei eine Basis für die Gameplay Logik entsteht, welche von beiden Clients (WinForms und der neue in Unity) verwendet werden können, da ich den WinForms Client noch nicht direkt sterben lassen möchte (da es vermutlich relativ lange bis zur ersten stabilen Unity Version dauern wird).

Dafür wird die neue Bibliothek [Conpiratio.Lib](https://github.com/Conspiratio/Conspiratio/tree/master/Conspiratio.Lib) aufgebaut und stetig erweitert. Ich übernehme dafür Logik vom alten Conspiratio WinForms Projekt.

Dieses Projekt ist abgeschlossen, wenn die gesamte Gameplay Logik, die heute bereits vorhanden ist, in diese Lib gewandert ist und vom Unity Projekt verwendet werden kann.

**Comment by schulzch** [comment]
Gibt es einen Branch für die WinForms-Version?

**Comment by SirTobyB** [comment]
> 
> 
> Gibt es einen Branch für die WinForms-Version?

Hi @schulzch,

derzeit gibt es dazu noch keinen Branch/Repo. Ich werde den WinForms Code veröffentlichen, sobald ich den Großteil der oben beschriebenen Vorbereitungen getroffen habe. Ich bin damit allerdings schon recht weit, es sollte daher nicht mehr allzu lange dauern.

Gruß
SirTobyB

**Comment by SirTobyB** [comment]
> 
> 
> Gibt es einen Branch für die WinForms-Version?

Nachtrag: Die WinForms Version ist mittlerweile unter https://github.com/Conspiratio/Conspiratio.WinForms online.

**Comment by SirTobyB** [comment]
Nuget Paket ist online (https://www.nuget.org/packages/Conspiratio.Lib/1.0.0) und im WinForms Client auch bereits eingebunden, daher schließe ich dieses Issue ab.
